/// <reference path="../TSS/lib/vsdoc/api.js" />
<!--#INCLUDE FILE="/AppEngine/CoreExt/ThingsSrv/base.tjs"-->
<%@ LANGUAGE=JavaScript %>
<%
	Response.clear();
	Response.write(function(){
		var result = {
				flag:true,
				buildlist:[]
			};	
		var buildlist = Request.QueryString("buildlist");
		var isall = Request.QueryString("isall"); 
		var kpiObject=TSS.JSON.decode(Server.ExecuteAPI("GET","/API/System/BCPS/ObjectClass/Building",""));
		var tc=new Date();
		for(var i=0;i<kpiObject.length;i++){
			if(isall=="false"){
				if(buildlist.indexOf(kpiObject[i].GroupID)==-1){
					continue;
				}
			}
			var item={name:kpiObject[i].GroupName,list:[],count:0};
			//var listNode=TSS.JSON.decode(Server.GetOPCFlatJSON(kpiObject[i].szOPCFullPath+".D"));
			
			//if(listNode.length==0){
				var d={};
				d["name"]="设施设备在线率";
				d["info"]=kpiObject[i].GroupName+"未发现雨水回用的关联设备，不做检查！";
				item.list.push(d);
				result.buildlist.push(item);											
				continue;	
			//}
			var online=0,nodecount=0;
			for(var j=0;j<listNode.length;j++){
				nodecount++;
				if(listNode[j].bOnLineFlag=="在线"){
					online++;
				}		
			}
			
			var percent=TSS.Utils.floatPrecision(online*100/nodecount,0);
			if(percent<85){
				item.count++;
				var d={};
				d["name"]="设施设备在线率";
				d["info"]=kpiObject[i].GroupName+"雨水回用的关联设备在线率偏低，为："+percent+"%！";
				item.list.push(d);			
			}else{	
				var d={};
				d["name"]="设施设备在线率";
				d["info"]=kpiObject[i].GroupName+"雨水回用的关联设备在线率为："+percent+"%！";
				item.list.push(d);	
			}

			var nodeTree=TSS.JSON.decode(Server.GetOPCFlatJSON(kpiObject[i].szOPCFullPath+".D.KPI"));
			if(nodeTree.length==0){
				var d={};
				d["name"]="设施设备在线率";
				d["info"]=kpiObject[i].GroupName+"未发现雨水回用的关联设备，不做检查！";
				item.list.push(d);
				result.buildlist.push(item);											
				continue;	
			}else{
				//雨水回用——待机预警及成本预警
				var t1 = tc.DateAdd("d",-1);
				var t2 = tc;
				var TotalW=0;
				var RainWater=0;
				var UpWater=0;
				var RainPumpElect=0;
				//自来水总量
				var restUrl="/API/System/IBMS/Mining/Statistics/Day?keyvalue=TotalWater&iscache=true&groupby=NodeObject&NodeFullTag="+kpiObject[i].szOPCFullPath+".D.KPI$&startTime="+t1.Format("yyyy-MM-dd hh:mm:ss")+"&endTime="+t2.Format("yyyy-MM-dd hh:mm:ss");
				var restObject=TSS.JSON.decode(TSS.Utils.ExcuteAPI("GET",restUrl));
				if(restObject.flag)
				{
					if(restObject.data.length>0
						&& restObject.data[0].value.DayMeasure!=null)
					{
						TotalW=restObject.data[0].value.DayMeasure;
					}
				}
				//雨水使用量
				var restUrl="/API/System/IBMS/Mining/Statistics/Day?keyvalue=RainWater&iscache=true&groupby=NodeObject&NodeFullTag="+kpiObject[i].szOPCFullPath+".D.KPI$&startTime="+t1.Format("yyyy-MM-dd hh:mm:ss")+"&endTime="+t2.Format("yyyy-MM-dd hh:mm:ss");
				var restObject=TSS.JSON.decode(TSS.Utils.ExcuteAPI("GET",restUrl));
				if(restObject.flag)
				{
					if(restObject.data.length>0
						&& restObject.data[0].value.DayMeasure!=null)
					{
						RainWater=restObject.data[0].value.DayMeasure;
					}
				}
				//补水使用量
				var restUrl="/API/System/IBMS/Mining/Statistics/Day?keyvalue=UpWater&iscache=true&groupby=NodeObject&NodeFullTag="+kpiObject[i].szOPCFullPath+".D.KPI$&startTime="+t1.Format("yyyy-MM-dd hh:mm:ss")+"&endTime="+t2.Format("yyyy-MM-dd hh:mm:ss");
				var restObject=TSS.JSON.decode(TSS.Utils.ExcuteAPI("GET",restUrl));
				if(restObject.flag)
				{
					if(restObject.data.length>0
						&& restObject.data[0].value.DayMeasure!=null)
					{
						UpWater=restObject.data[0].value.DayMeasure;
					}
				}
				//计算节约费
				var restUrl="/API/System/IBMS/Mining/Statistics/Day?keyvalue=TotalE&iscache=true&groupby=NodeObject&NodeFullTag="+kpiObject[i].szOPCFullPath+".D.KPI$&startTime="+t1.Format("yyyy-MM-dd hh:mm:ss")+"&endTime="+t2.Format("yyyy-MM-dd hh:mm:ss");
				var restObject=TSS.JSON.decode(TSS.Utils.ExcuteAPI("GET",restUrl));
				if(restObject.flag)
				{
					if(restObject.data.length>0
						&& restObject.data[0].value.DayMeasure!=null)
					{
						RainPumpElect=restObject.data[0].value.DayMeasure;
						if(RainWater<=0.1)
						{
							if(RainPumpElect>1)
							{
								item.count++;
								var alarmText=kpiObject[i].GroupName+"雨水回用系统处于空耗运行中，一天浪费："+TSS.Utils.formatNumber(RainPumpElect,"0.0")+"度电，建议关闭雨水回用系统水泵！！！";
								var d={};
								d["name"]="运行成本分析";
								d["info"]=alarmText;
								item.list.push(d);
							}
							else
							{
								var d={};
								d["name"]="运行成本分析";
								d["info"]=kpiObject[i].GroupName+"雨水回用系统运行能耗为："+TSS.Utils.formatNumber(RainPumpElect,"0.0")+"度电";
								item.list.push(d);
							}
						}
						else if(RainWater<=UpWater)
						{
							var alarmText=kpiObject[i].GroupName+"雨水回用系统处于异常运行中，最近自来水补水量("+UpWater+"吨)超过雨水使用量("+RainWater+"吨)，请检查系统操作是否正常！！！";
							item.count++;
							var d={};
							d["name"]="运行成本分析";
							d["info"]=alarmText;
							item.list.push(d);
						}
						else
						{
							var mony=(UpWater*kpiObject[i].ObjectInfo.WaterPrice+RainPumpElect*kpiObject[i].ObjectInfo.ElectPrice)/RainWater;
							if(mony>kpiObject[i].ObjectInfo.WaterPrice)
							{
								var alarmText=kpiObject[i].GroupName+"雨水回用系统当前日用水量："+RainWater+"吨，日用电量："+TSS.Utils.formatNumber(RainPumpElect,"0.0")+"度，单位运行成本为："+TSS.Utils.formatNumber(mony,"0.0")+"元/吨，已超过标准水价："+TSS.Utils.formatNumber(kpiObject[i].ObjectInfo.WaterPrice,"0.0")+"元/吨，请紧急检修！！！";
								item.count++;
								var d={};
								d["name"]="运行成本分析";
								d["info"]=alarmText;
								item.list.push(d);
							}
							else
							{
								var d={};
								d["name"]=kpiObject[i].GroupName+"雨水回用系统运行成本为："+TSS.Utils.formatNumber(mony,"0.0")+"元/吨",
								d["info"]=alarmText;
								item.list.push(d);
							}
						}
					}
				}
				result.buildlist.push(item);						
			}
			
		}
		result.buildlist.sort(function(x, y){
				return (x.count < y.count) ? 1 : -1;
		});
		return TSS.JSON.encode(result);
		
	}());
	Response.ContentType = "text/plain";
%>