<!--#INCLUDE FILE="/AppEngine/CoreExt/ThingsSrv/base.tjs"-->
<%@ LANGUAGE=JavaScript %>
<%
	Response.clear();
	Response.write(function(){
		var result= TSS.JSON.decode(Server.ExecuteAPI("PUT","/API/Times","enable=true&tag=syncUser&name=同步数据中心用户库&describe=检查同步数据中心用户库&type=0&year=0&month=0&day=0&hour=1&minute=0&second=0&path=/Webapp/UserManager/SRV/syncUser.tjs"));
		if(!result.flag)
		{
			return TSS.JSON.encode(result);
		}
		//
		return "OK";
	}());
	Response.ContentType = "text/plain";
%>